<?php

namespace App\UI\Components\Admin\Stand;

use App\Domain\Location\Location;
use App\Domain\Stand\Stand;
use App\Domain\Stand\StandService;
use App\UI\Components\Base\BaseComponent;
use App\UI\Form\BaseForm;
use Nette\Utils\ArrayHash;

class StandForm extends BaseComponent
{
    private StandService $standService;
    private ?string $cancelUrl;
    private ?Stand $stand;

    public function __construct(
        StandService $standService,
        ?Stand      $stand,
        string      $cancelUrl = null,
    )
    {
        $this->standService = $standService;
        $this->stand = $stand;
        $this->cancelUrl = $cancelUrl;
    }

    public function render(mixed $params = null): void
    {
        if ($this->stand)
        {
            $this['form']->setDefaults([
                'name'      => $this->stand->getName(),
                'latitude'  => $this->stand->getLocation()->getLatitude(),
                'longitude' => $this->stand->getLocation()->getLongitude(),
            ]);
        }

        parent::render($params); // TODO: Change the autogenerated stub
    }

    public function createComponentForm(): BaseForm
    {
        $form = new BaseForm();

        $form->addText('name', 'Název')
            ->setRequired()
        ;
        $form->addFloat('latitude', 'Zeměpisná šířka')
            ->setRequired()
        ;
        $form->addFloat('longitude', 'Zeměpisná délka')
            ->setRequired()
        ;

        $form->addSubmit('send', 'Uložit');

        if ($this->cancelUrl)
        {
            $form->addCancelButton($this->cancelUrl);
        }

        $form->onSuccess[] = [$this, 'formSucceeded'];

        return $form;
    }

    public function formSucceeded(BaseForm $form, ArrayHash $values): void
    {
        try
        {
            if($this->stand)
            {
                $this->standService->updateStand($this->stand, $values['name'], new Location($values['latitude'], $values['longitude']));
            } else
            {
                $this->standService->createStand($values['name'], new Location($values['latitude'], $values['longitude']));
            }

            $this->flashSuccess('Stojan úspěšně uložen.');
        }
        catch (\Exception $e)
        {
            $this->flashError('Při ukládání se vyskytla chyba.');
        }
    }
}