version: '3.8'
services:
  php-apache-environment:
    container_name: "${COMPOSE_PROJECT_NAME}_apache"
    image: thecodingmachine/php:8.2-v4-apache
    volumes:
      - ./../:/var/www/html
    ports:
      - "${PORT_APACHE}:80"   # http
    links:
      - database
    depends_on:
      - database
    env_file:
      - php.env

  database:
    image: mariadb:latest
    container_name: "${COMPOSE_PROJECT_NAME}_mariadb"
    ports:
      - "${PORT_MARIADB}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pristup_123
      MYSQL_DATABASE: PIA-SP
    volumes:
      - ./../sql/docker_init/initDockerDatabase.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    container_name: "${COMPOSE_PROJECT_NAME}_phpmyadmin"
    image: phpmyadmin:latest
    depends_on:
      - database
    links:
      - database
    ports:
      - "${PORT_PHP_MY_ADMIN}:8080"
    environment:
      PMA_HOST: database
