version: '3.8'
services:
  php-apache-environment:
    container_name: "${COMPOSE_PROJECT_NAME}_apache"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../:/var/www/html
    ports:
      - "${PORT_APACHE}:80"   # http
      - "${PORT_WEBSOCKET}:8080"
      - "${PORT_WEBSOCKET_ZMQ}:5555"
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    env_file:
      - php.env

  database:
    image: mariadb:latest
    container_name: "${COMPOSE_PROJECT_NAME}_mariadb"
    ports:
      - "${PORT_MARIADB}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pristup_123
      MYSQL_DATABASE: PIA-SP
    volumes:
      - ./../sql/docker_init/initDockerDatabase.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    container_name: "${COMPOSE_PROJECT_NAME}_phpmyadmin"
    image: phpmyadmin:latest
    depends_on:
      - database
    links:
      - database
    ports:
      - "${PORT_PHP_MY_ADMIN}:8080"
    environment:
      PMA_HOST: database

  redis:
    image: redis:latest
    container_name: "${COMPOSE_PROJECT_NAME}_redis"
    ports:
      - "${PORT_REDIS}:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
