<?php declare(strict_types = 1);

namespace App\UI\Modules\Base;

use App\Domain\Config\ConfigService;
use App\Model\Latte\TemplateProperty;
use App\Model\Security\SecurityUser;
use App\Model\Utils\FlashMessage;
use App\UI\Components\Base\BaseComponent;
use App\UI\Control\TFlashMessage;
use App\UI\Control\TModuleUtils;
use Contributte\Application\UI\Presenter\StructuredTemplates;
use Contributte\Translation\LocalesResolvers\Session;
use Contributte\Translation\PrefixedTranslator;
use Contributte\Translation\Translator;
use Nette\Application\UI\Presenter;
use Nette\Bootstrap\Configurator;
use Nette\ComponentModel\IComponent;

/**
 * @property-read TemplateProperty $template
 * @property-read SecurityUser $user
 */
abstract class BasePresenter extends Presenter
{
    /** @var ConfigService $configService @inject */
    public ConfigService $configService;

    public readonly string $webSocketAddress;

    /** @var Translator @inject */
    public Translator $translator;

    public PrefixedTranslator $presenterTranslator;

    /** @var Session @inject */
    public $translatorSessionResolver;
    public function startup()
    {
        $this->template->appVersion = '0.1';

        $this->webSocketAddress = $this->configService->getWebSocketAddress();
        $this->template->webSocketAddress = $this->webSocketAddress;

        $name = explode(':', $this->getName());
        $this->presenterTranslator = $this->translator->createPrefixedTranslator(strtolower($name[0]) . '.' . lcfirst($name[1] . 'Presenter'));

        parent::startup();
    }

    public function handleChangeLocale(string $locale): void
    {
        $this->translatorSessionResolver->setLocale($locale);
        $this->redirect('this');
    }

    public function addComponent(IComponent $component, ?string $name, ?string $insertBefore = null)
    {
        if ($component instanceof BaseComponent)
        {
            $component->onFlash[] = function(FlashMessage $flashMessage) {
                $this->flash($flashMessage);
            };
        }

        $container = parent::addComponent($component, $name, $insertBefore); // TODO: Change the autogenerated stub
        return $container;
    }

    use StructuredTemplates;
	use TFlashMessage;
	use TModuleUtils;

}
