<?php declare(strict_types = 1);

namespace App\UI\Modules\Base;

use App\Model\Latte\TemplateProperty;
use App\Model\Security\SecurityUser;
use App\Model\Utils\FlashMessage;
use App\UI\Components\Base\BaseComponent;
use App\UI\Control\TFlashMessage;
use App\UI\Control\TModuleUtils;
use Contributte\Application\UI\Presenter\StructuredTemplates;
use Contributte\Translation\LocalesResolvers\Session;
use Nette\Application\UI\Presenter;
use Nette\ComponentModel\IComponent;
use Nette\Localization\ITranslator;

/**
 * @property-read TemplateProperty $template
 * @property-read SecurityUser $user
 */
abstract class BasePresenter extends Presenter
{

    /** @var ITranslator @inject */
    public $translator;

    /** @var Session @inject */
    public $translatorSessionResolver;
    public function startup()
    {
        $this->template->appVersion = '0.1';
        parent::startup();
    }

    public function handleChangeLocale(string $locale): void
    {
        $this->translatorSessionResolver->setLocale($locale);
        $this->redirect('this');
    }

    public function addComponent(IComponent $component, ?string $name, ?string $insertBefore = null)
    {
        if ($component instanceof BaseComponent)
        {
            $component->onFlash[] = function(FlashMessage $flashMessage) {
                $this->flash($flashMessage);
            };
        }

        $container = parent::addComponent($component, $name, $insertBefore); // TODO: Change the autogenerated stub
        return $container;
    }

    use StructuredTemplates;
	use TFlashMessage;
	use TModuleUtils;

}
